### ISSUE TITLE
"ErrorException Undefined index: contributors" on route /repository/{name}

### ISSUE THREAD

**Issue by pauly4it** [modess/git-pretty-stats#35]
I've set up git-pretty-stats on a per-project installation of homestead. The home view works fine, showing the two repos I've cloned into the repositories directory.

When I click on one of the repositories, I see the loading bar at the top of the page and then nothing happens. The console shows a 500 being returned from repository/repo_name. So I browsed to repository/repo_name and got "ErrorException Undefined index: contributors".

Here's the stack trace from the logs:

```
[2015-10-16 23:37:39] local.ERROR: exception 'ErrorException' with message 'Undefined index: contributors' in /home/vagrant/git-pretty-stats/app/GitPrettyStats/StatisticsFormatter.php:43
Stack trace:
#0 /home/vagrant/git-pretty-stats/app/GitPrettyStats/StatisticsFormatter.php(43): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/home/vagrant/g...', 43, Array)
#1 /home/vagrant/git-pretty-stats/app/GitPrettyStats/StatisticsFormatter.php(53): GitPrettyStats\StatisticsFormatter->statistics('contributors')
#2 /home/vagrant/git-pretty-stats/app/GitPrettyStats/Repository.php(71): GitPrettyStats\StatisticsFormatter->contributors()
#3 /home/vagrant/git-pretty-stats/app/controllers/RepositoryController.php(49): GitPrettyStats\Repository->statistics()
#4 [internal function]: RepositoryController->show('lifesparq')
#5 /home/vagrant/git-pretty-stats/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#6 /home/vagrant/git-pretty-stats/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('show', Array)
#7 /home/vagrant/git-pretty-stats/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(RepositoryController), Object(Illuminate\Routing\Route), 'show')
#8 /home/vagrant/git-pretty-stats/vendor/laravel/framework/src/Illuminate/Routing/Router.php(934): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'RepositoryContr...', 'show')
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('lifesparq')
#10 /home/vagrant/git-pretty-stats/vendor/laravel/framework/src/Illuminate/Routing/Route.php(104): call_user_func_array(Object(Closure), Array)
#11 /home/vagrant/git-pretty-stats/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /home/vagrant/git-pretty-stats/vendor/laravel/framework/src/Illuminate/Routing/Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 /home/vagrant/git-pretty-stats/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /home/vagrant/git-pretty-stats/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /home/vagrant/git-pretty-stats/vendor/barryvdh/laravel-cors/src/Barryvdh/Cors/CorsMiddleware.php(33): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#16 /home/vagrant/git-pretty-stats/vendor/laravel/framework/src/Illuminate/Http/FrameGuard.php(38): Barryvdh\Cors\CorsMiddleware->handle(Object(Illuminate\Http\Request), 1, true)
#17 /home/vagrant/git-pretty-stats/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#18 /home/vagrant/git-pretty-stats/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#19 /home/vagrant/git-pretty-stats/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#20 /home/vagrant/git-pretty-stats/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#21 /home/vagrant/git-pretty-stats/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#22 /home/vagrant/git-pretty-stats/public/index.php(49): Illuminate\Foundation\Application->run()
#23 {main} [] []
```

Any ideas on what's going wrong?

**Comment by modess** [comment]
This bug has already been reported at https://github.com/modess/git-pretty-stats/issues/32, please continue contributing there!
